# The 73 references pasted from Manuscript_CSP_revised.docx, as (first_author_surname, year, title) tuples.
MANUSCRIPT_REFS = [
    ("Baker", 2010, "Research Synthesis: AAPOR Report on Online Panels"),
    ("Bennett", 2017, "Conservation social science: Understanding and integrating human dimensions to improve conservation"),
    ("Betancort Cabrera", 2020, "White paper on implementing the FAIR principles for data in the social, behavioural, and economic sciences"),
    ("Bonett", 2000, "Sample size requirements for estimating pearson, Kendall and Spearman correlations"),
    ("Boren", 2025, "Does psychic numbing apply to endangered species conservation? The case of the Peregrine Falcon in Berkeley, California"),
    ("Braun", 2006, "Using thematic analysis in psychology"),
    ("British Ecological Society", 2026, "Better Science Guides for Ecology Fieldwork and Research"),
    ("Browne-Nunez", 2015, "Tolerance of wolves in Wisconsin: A mixed-methods examination of policy effects on attitudes and behavioral inclinations"),
    ("Callahan", 2019, "Using the Phylo Card Game to advance biodiversity conservation in an era of Pokemon"),
    ("Carroll", 2020, "The CARE Principles for Indigenous Data Governance"),
    ("Clayton", 2021, "Cross-Cultural Validation of A Revised Environmental Identity Scale"),
    ("Clayton", 2016, "Expanding the role for psychology in addressing environmental challenges"),
    ("Cortes-Avizanda", 2018, "Stakeholders perceptions of the endangered Egyptian vulture: Insights for conservation"),
    ("Dayer", 2020, "Applying conservation social science to study the human dimensions of Neotropical bird conservation"),
    ("Dillman", 2011, "Mail and Internet Surveys: The Tailored Design Method"),
    ("Dinat", 2019, "Eco-xenophobia among rural populations: The Great-tailed Grackle as a contested species in Guanacaste, Costa Rica"),
    ("Dunlap", 2000, "New Trends in Measuring Environmental Attitudes: Measuring Endorsement of the New Ecological Paradigm: A Revised NEP Scale"),
    ("Dylong", 2024, "Priming attitudes toward immigrants: Implications for migration research and survey design"),
    ("Echeverri", 2017, "How messaging shapes attitudes toward sea otters as a species at risk"),
    ("Echeverri", 2021, "Avian cultural services peak in tropical wet forests"),
    ("Echeverri", 2019, "Iconic manakins and despicable grackles: Comparing cultural ecosystem services and disservices across stakeholders in Costa Rica"),
    ("Edunov", 2018, "Understanding Back-Translation at Scale"),
    ("ElHaffar", 2020, "Towards closing the attitude-intention-behavior gap in green consumption"),
    ("Fairbairn", 2023, "Eye-tracking in map use, map user and map usability research: What are we looking for?"),
    ("Garrison", 2013, "Genomic Justice for Native Americans: Impact of the Havasupai Case on Genetic Research"),
    ("Goodson", 2025, "Fostering bird friendly cities: Multispecies justice through pro-environmental behaviors"),
    ("Goritz", 2010, "Using lotteries, loyalty points, and other incentives to increase participant response and completion"),
    ("Hayes", 2025, "Conversing with qualitative data: Enhancing qualitative research through large language models"),
    ("Jeong", 2023, "Exhaustive or exhausting? Evidence on respondent fatigue in long surveys"),
    ("Jobin", 2019, "The global landscape of AI ethics guidelines"),
    ("De-Nova", 2023, "Evolutionary clustering in Neotropical biocultural heritage: The Huastec Mayan useful plants"),
    ("Kay", 2025, "Why you shouldn't trust data collected on MTurk"),
    ("Keren", 1993, "Between- or within-subjects design: A methodological dilemma"),
    ("Kizilcec", 2018, "Social influence and reciprocity in online gift giving"),
    ("Klain", 2020, "Octopus's garden under the blade: Boosting biodiversity increases willingness to pay for offshore wind in the United States"),
    ("Krippendorff", 2018, "Content Analysis: An Introduction to Its Methodology"),
    ("Langhans", 2025, "Watching from your own residence makes it more accessible: Identifying supports and barriers to participatory science"),
    ("Langhans", 2025, "Urban community gardens foster positive human-avian interactions across an income gradient in San Francisco"),
    ("Luo", 2019, "Motivated attention in climate change perception and action"),
    ("Mandle", 2021, "Increasing decision relevance of ecosystem service science"),
    ("Manfredo", 2021, "Social value shift in favour of biodiversity conservation in the United States"),
    ("Manfredo", 2003, "Why Are Public Values Toward Wildlife Changing?"),
    ("Mariano", 2018, "Multivariate cyclical data visualization using radial visual rhythms: A case study in phenology analysis"),
    ("Miller", 2025, "Accessibility, disability, and inclusive instrument design"),
    ("Naito", 2022, "An integrative framework for transformative social change: A case in global wildlife trade"),
    ("Niesner", 2024, "The coyote in the cloud"),
    ("Norman", 2010, "Likert scales, levels of measurement and the laws of statistics"),
    ("Olivos", 2011, "Psychometric properties of the Environmental Identity Scale (EID)"),
    ("Page", 2021, "The PRISMA 2020 statement: An updated guideline for reporting systematic reviews"),
    ("Perez", 2021, "Design and psychometric properties of the BAtSS: A new tool to assess attitudes towards bats"),
    ("Pullin", 2006, "Guidelines for systematic review in conservation and environmental management"),
    ("Putnick", 2016, "Measurement invariance conventions and reporting"),
    ("Salazar", 2022, "Testing the influence of visual framing on engagement and pro-environmental action"),
    ("Schreck Reis", 2013, "Public perception of invasive plant species"),
    ("Schroeder", 2025, "Large Language Models in Qualitative Research: Uses, Tensions, and Intentions"),
    ("Secules", 2021, "Positionality practices and dimensions of impact on equity research"),
    ("Sieber", 1995, "Deception Methods in Psychology: Have They Changed in 23 Years?"),
    ("Steele", 2006, "Math is Hard! The effect of gender priming on women's attitudes"),
    ("Stern", 2018, "Social Science Theory for Environmental Sustainability: A Practical Guide"),
    ("Sun", 2010, "A Comprehensive Review of Effect Size Reporting and Interpreting Practices in Academic Journals in Education and Psychology"),
    ("Tavakol", 2011, "Making sense of Cronbach's alpha"),
    ("Teel", 2010, "Understanding the diversity of public interests in wildlife conservation"),
    ("Tenkanen", 2017, "Instagram, Flickr, or Twitter: Assessing the usability of social media data for visitor monitoring in protected areas"),
    ("Turner", 2021, "Grounded theory: What makes a grounded theory study?"),
    ("van den Akker", 2024, "Preregistration in practice: A comparison of preregistered and non-preregistered studies in psychology"),
    ("Vaske", 2008, "Survey research and analysis: Applications in parks, recreation and human dimensions"),
    ("Vaske", 2019, "Survey research and analysis"),
    ("Verissimo", 2024, "Using digital mobile games to increase the support for nature conservation"),
    ("Wagner", 2003, "Ethical review of research involving human subjects: When and why is IRB review necessary?"),
    ("Wardropper", 2021, "Conducting conservation social science surveys online"),
    ("Whitehouse-Tedd", 2021, "Evaluation of the use of psychometric scales in human-wildlife interaction research to determine attitudes and tolerance toward wildlife"),
    ("Williams", 2024, "The Elephant Queen: Can a nature documentary help to increase tolerance towards elephants?"),
    ("Willis", 2018, "Development and Pilot Testing of a Decision Aid for Genomic Research Participants"),
    ("Wilson", 2022, "Classification of open-ended responses to a research-based assessment using natural language processing"),
    ("Xiiem", 2019, "Decolonizing Research: Indigenous Storywork as Methodology"),
]

# NOTE: the pasted manuscript bibliography contains 75 distinct entries, not the
# 73 originally stated in the Fig2 spec. Using the actual count rather than the
# stale figure.
